In [2]:
import numpy as np
# NumPy is used to work with arrays. The array object in NumPy is called ndarray.

#We can create a NumPy ndarray object by using the array() function.

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
print(np.__version__) # checking numpy version

1.18.5


In [9]:
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
import numpy as np
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [11]:
# 0-D arrays
import numpy as np
arr = np.array(42)

print(arr)

42


In [13]:
# 1-D Arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [15]:
# 2-D Arrays
# an array has 1-d arrays as its elements is called 2-d array
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [1]:
# check number of dimensions using ndim

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
# access array elements

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0]) # printing first element of array
print(arr[2]) # printing third element of array

print(arr[0] + arr[2]) # adding first and second element in array

1
3
4


In [7]:
# Access 2-D Arrays

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print("2nd element on 1st row", arr[0][1])
print("2nd element on 2nd row", arr[1][1])

2nd element on 1st row 2
2nd element on 2nd row 5


In [10]:
# Access 3-D Arrays

import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,0]) # accessing 1st element on 2nd array of 1st array
print(arr[1,1,2]) # accessing 3rd element of 2nd array of 2nd array

4
12


In [13]:
# negative indexing
import numpy as np 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("last element from 2 dim:", arr[1,-1])


last element from 2 dim: 10


In [14]:
# slicing arrays
# Slice elements from index 1 to index 5 from the following array:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [15]:
# Slice elements from index 4 to the end of the array:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [17]:
# Slice elements from the beginning to index 4 (not included):
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])

[1 2 3 4]


In [20]:
# Slice from the index 3 from the end to index 1 from the end:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])


[5 6]


In [21]:
# Return every other element from index 1 to index 5
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [22]:
# Return every other element from the entire array:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [23]:
# Slicing 2-D Arrays
# From the second element, slice elements from index 1 to index 4 (not included)
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


In [24]:
# Slicing 2-D Arrays 
# From both elements, return index 2

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:,2])

[3 8]


In [25]:
# Slicing 2-D Arrays 
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:, 1:4])

[[2 3 4]
 [7 8 9]]


In [1]:
# Checking the Data Type of an Array
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [2]:
# Get the data type of an array containing strings
import numpy as np
arr = np.array(["apple", "banana", "cherry"])

print(arr.dtype)

<U6


In [4]:
# Creating Arrays With a Defined Data Type
import numpy as np

arr = np.array([1, 2, 3, 4], dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
# Create an array with data type 4 bytes integer
import numpy as np
arr = np.array([1, 2, 3, 4], dtype="i4")

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [6]:
# Converting Data Type on Existing Arrays
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype("i")

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
# Change data type from integer to boolean
import numpy as np
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


In [9]:
# Make a copy, change the original array, and display both arrays
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
# Make a view, change the original array, and display both arrays
import numpy as np
arr = np.array([1,2,3,4,4])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  4]
[42  2  3  4  4]


In [12]:
# Make a view, change the view, and display both arrays
import numpy as np 
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [13]:
# check if array owns the data
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [15]:
# Get the Shape of an Array
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [17]:
import numpy as np

arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)
print("shape of arr", arr.shape)

[[[[[1 2 3 4 5]]]]]
shape of arr (1, 1, 1, 1, 5)


In [41]:
# Reshape From 1-D to 2-D
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
# Reshape From 1-D to 3-D

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [43]:
# returns copy or view
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [47]:
# Unknown Dimension
# You are allowed to have one "unknown" dimension.

# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

# Pass -1 as the value, and NumPy will calculate this number for you.

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,2,-1)

print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [48]:
# Convert the array into a 1D array
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [49]:
# Iterating Arrays
import numpy as np

arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [50]:
# Iterating 2-D Arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [52]:
# Iterate on each scalar element of the 2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [54]:
# Iterating 3-D Arrays
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [56]:
# Iterate down to the scalars 3-d array

import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [58]:
# Iterating Arrays Using nditer()
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [60]:
# Iterating Array With Different Data Types

import numpy as np
arr = np.array([1,2,3])

for x in np.nditer(arr, flags=["buffered"], op_dtypes=["S"]):
    print(x)

b'1'
b'2'
b'3'


In [61]:
# Iterating With Different Step Size
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [63]:
# Enumerate on following 1D arrays elements
import numpy as np
arr = np.array([1,2,3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [64]:
# Enumerate on following 2D array's elements
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [2]:
# Joining NumPy Arrays
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [3]:
# Join two 2-D arrays along rows (axis=1)

import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
# Joining Arrays Using Stack Functions
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis= 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
# Stacking Along Rows

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
# Stacking Along Columns
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# Stacking Along Height (depth)
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [11]:
# Splitting NumPy Arrays
# We use array_split() for splitting arrays
import numpy as np
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 3) # spliting array in 3 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
# Split the array in 4 parts:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4) # spliting array in 4 parts
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [13]:
# Split Into Arrays
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [14]:
# Splitting 2-D Arrays
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [15]:
# Split the 2-D array into three 2-D arrays.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [16]:
# Split the 2-D array into three 2-D arrays along rows.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [20]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr = np.hsplit(arr, 3)
print(newarr)

# Similar alternates to vstack() and dstack() are available as vsplit() and dsplit()


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [21]:
# Searching Arrays
import numpy as np
arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [22]:
# Find the indexes where the values are even
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [24]:
# Find the indexes where the values are odd
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr% 2== 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [26]:
# The searchsorted() method is assumed to be used on sorted arrays
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 9)
print(x)

3


In [30]:
# Search From the Right Side
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7, side= "right")
print(x)

2


In [31]:
# Find the indexes where the values 2, 4, and 6 should be inserted
import numpy as np
arr = np.array([1,3,5,7])
x = np.searchsorted(arr, [2,4,6])
print(x)

[1 2 3]


In [32]:
# Sorting Arrays
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [33]:
# Sort the array alphabetically
import numpy as np
arr = np.array(["banana", "cherry", "apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [34]:
# Sort a boolean array
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [35]:
# Sorting a 2-D Array
import numpy as np
arr = np.array([[3,5,2],[8,10,6]])
print(np.sort(arr))

[[ 2  3  5]
 [ 6  8 10]]


In [36]:
# Filtering Arrays
# Create an array from the elements on index 0 and 2
import numpy as np

arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [43]:
# Creating the Filter Array
import numpy as np
arr5 = np.array([41,42,43,44,45,46,47,48,49,50])

filter_arr = []

for num in arr5:
    if num > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
new_arr = arr5[filter_arr]
print(filter_arr)
print(newarr)
        

[False, False, True, True, True, True, True, True, True, True]
[43 44 45 46 47 48 49 50]


In [47]:
# Create a filter array that will return only even elements from the original array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])

filter_arr = []

for num in arr:
    if num % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(newarr)

[ 2  4  6  8 10]


In [48]:
# Creating Filter Directly From Array
import numpy as np

arr = np.array([41,42,43,44,45,46])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(newarr)

[43 44 45 46]


In [49]:
# Create a filter array that will return only even elements from the original array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(newarr)

[ 2  4  6  8 10]
